version: 2
jobs:
  build:
    working_directory: ~/ekanite/src/github.com/ekanite/ekanite
    docker:
      - image: circleci/golang:1.13

    steps:
        - checkout
        - run: go vet .
        - run: bash gofmt.sh
        - run: go get -t -d -v ./...
        - run: go test -timeout 60s -v ./...
        - run:
            command: go test -race -timeout 120s -v ./...
            environment:
                GORACE: "halt_on_error=1"
